version: '3.8'
services:
  traefik:
    restart: always
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
#      - "--log.level=DEBUG"
#      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:4580"
    ports:
      - "4580:4580"
#      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  puzzlesolver-frontend:
    restart: always
    container_name: puzzlesolver-frontend
    build:
      context: ./puzzlesolver-frontend
      dockerfile: Dockerfile
    volumes:
      - ./puzzlesolver-frontend/html:/var/www/html/
    labels:
      - "traefik.http.routers.puzzlesolver-frontend-router.entrypoints=web"
      - "traefik.http.routers.puzzlesolver-frontend-router.rule=(PathPrefix(`/puzzlesolver`))"
      - "traefik.http.routers.puzzlesolver-frontend-router.service=puzzlesolver-frontend-service"
      - "traefik.http.services.puzzlesolver-frontend-service.loadbalancer.server.port=80"
      # Add trailing slash. Strip prefix before routing.
      - "traefik.http.routers.puzzlesolver-frontend-router.middlewares=strip-prefix"
      - "traefik.http.middlewares.strip-prefix.chain.middlewares=strip-prefix-1,strip-prefix-2"
      - "traefik.http.middlewares.strip-prefix-1.redirectregex.regex=^(https?://[^/]+/[a-z0-9_]+)$$"
      - "traefik.http.middlewares.strip-prefix-1.redirectregex.replacement=$${1}/"
      - "traefik.http.middlewares.strip-prefix-1.redirectregex.permanent=true"
      - "traefik.http.middlewares.strip-prefix-2.stripprefixregex.regex=/[a-z0-9_]+"
  node:
    restart: always
    container_name: node
    build:
      context: ./resume_react_server
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.resume-react-server-router.entrypoints=web"
      - "traefik.http.routers.resume-react-server-router.rule=PathPrefix(`/`)"
      - "traefik.http.routers.resume-react-server-router.service=resume-react-server-service"
      - "traefik.http.services.resume-react-server-service.loadbalancer.server.port=3001"
  puzzlesolver_api:
    restart: always
    container_name: puzzlesolver_api
    build:
      context: ./puzzlesolver-api-spring-boot
      dockerfile: Dockerfile
    ports:
      - "9091:8080"
    labels:
      - "traefik.http.routers.puzzlesolver-api-router.entrypoints=web"
      - "traefik.http.routers.puzzlesolver-api-router.rule=(PathPrefix(`/psapi`))"
      - "traefik.http.routers.puzzlesolver-api-router.service=puzzlesolver-api-service"
      - "traefik.http.services.puzzlesolver-api-service.loadbalancer.server.port=8080"
  defaultroot:
    restart: always
    container_name: "note-app-defaultroot"
    build:
      context: ./note_app/defaultroot
      dockerfile: Dockerfile
    volumes:
      - ./note_app/data/defaultroot/data:/usr/src/app/data
    labels:
      - "traefik.http.routers.note-app-defaultroot-router.entrypoints=web"
      - "traefik.http.routers.note-app-defaultroot-router.rule=PathPrefix(`/notes`)"
      - "traefik.http.routers.note-app-defaultroot-router.service=note-app-defaultroot-service"
      - "traefik.http.services.note-app-defaultroot-service.loadbalancer.server.port=3000"
    environment:
      - BASE_DIR=/notes
  software:
    restart: always
    container_name: "software"
    build:
      context: ./note_app/ui
      dockerfile: Dockerfile
    volumes:
      - ./note_app/data/software/data:/usr/src/app/data
    labels:
      - "traefik.http.routers.note-app-software-router.entrypoints=web"
      - "traefik.http.routers.note-app-software-router.rule=PathPrefix(`/notes/software`)"
      - "traefik.http.routers.note-app-software-router.service=note-app-software-service"
      - "traefik.http.services.note-app-software-service.loadbalancer.server.port=3000"
    environment:
      - BASE_DIR=/notes/software
      - APP_NAME=Software
  keyboard-ui:
    restart: always
    container_name: keyboard-ui
    build:
      context: ./keyboard_ui
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.keyboard-ui-router.entrypoints=web"
      - "traefik.http.routers.keyboard-ui-router.rule=(PathPrefix(`/keyboard`))"
      - "traefik.http.routers.keyboard-ui-router.service=keyboard-ui-service"
      - "traefik.http.services.keyboard-ui-service.loadbalancer.server.port=3333"
      # Add trailing slash. Strip prefix before routing.
      - "traefik.http.routers.keyboard-ui-router.middlewares=strip-prefix"
      - "traefik.http.middlewares.strip-prefix.chain.middlewares=strip-prefix-1,strip-prefix-2"
      - "traefik.http.middlewares.strip-prefix-1.redirectregex.regex=^(https?://[^/]+/[a-z0-9_]+)$$"
      - "traefik.http.middlewares.strip-prefix-1.redirectregex.replacement=$${1}/"
      - "traefik.http.middlewares.strip-prefix-1.redirectregex.permanent=true"
      - "traefik.http.middlewares.strip-prefix-2.stripprefixregex.regex=/[a-z0-9_]+"
