version: '3.8'
services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
#      - "--log.level=DEBUG"
#      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:4480"
    ports:
      - "4480:4480"
#      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  puzzlesolver_frontend_image:
    container_name: puzzlesolver_frontend_image
    build:
      context: ./puzzlesolver_frontend_image
      dockerfile: Dockerfile
    volumes:
      - ./puzzlesolver_frontend_image/html:/var/www/html/
    labels:
      - "traefik.http.routers.puzzlesolver-frontend-image-router.entrypoints=web"
      - "traefik.http.routers.puzzlesolver-frontend-image-router.rule=(Host(`localhost`) && PathPrefix(`/puzzlesolver-frontend`))"
      - "traefik.http.routers.puzzlesolver-frontend-image-router.service=puzzlesolver-frontend-image-service"
      - "traefik.http.services.puzzlesolver-frontend-image-service.loadbalancer.server.port=80"
  apache:
    container_name: apache
    build:
      context: ./apache
      dockerfile: Dockerfile
    volumes:
      - ./apache/html:/var/www/html/
    labels:
      - "traefik.http.routers.apache-router.entrypoints=web"
      - "traefik.http.routers.apache-router.rule=Host(`localhost`)"
      - "traefik.http.routers.apache-router.service=apache-service"
      - "traefik.http.services.apache-service.loadbalancer.server.port=80"
  puzzlesolver_api:
    container_name: puzzlesolver_api
#    image: puzzlesolver-api-spring-boot
    build:
      context: ./puzzlesolver-api-spring-boot
      dockerfile: Dockerfile
    ports:
      - "9091:8080"
    labels:
      - "traefik.http.routers.puzzlesolver-api-router.entrypoints=web"
      - "traefik.http.routers.puzzlesolver-api-router.rule=(Host(`localhost`) && PathPrefix(`/psapi`))"
      - "traefik.http.routers.puzzlesolver-api-router.service=puzzlesolver-api-service"
      - "traefik.http.services.puzzlesolver-api-service.loadbalancer.server.port=8080"
