-- INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('2022-10-07', '+2367', 'paycheck');
-- INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('2022-10-08', '-43', 'phone bill');
-- INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('2022-10-09', '-109', 'water bill');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/7', '+2367', 'paycheck');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/8', '-43', 'mobile');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/9', '-109', 'water');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/9', '-2172', 'mortgage');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/10', '-54', 'groceries');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/11', '-27', 'house gas');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/11', '-347', 'tithe');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/13', '-13', 'groceries');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/15', '-25', 'gas*trip');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/15', '-2', 'walmart water jug*trip');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/15', '-8', 'cook out*eating out');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/15', '-10', 'gas*trip');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/15', '-8', 'cook out*eating out');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/17', '-20', 'costco wipers and spinach');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/19', '-200', 'chase*credit card');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/20', '-13', 'groceries');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/21', '+2373', 'paycheck');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/21', '-7', 'walmart candy');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/21', '-8', 'cook out*eating out');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/22', '-5', 'gas*motorcycle');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/22', '-17', 'lyft*acyclical*motorcycle break down');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/23', '-24', 'gas');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/23', '-102', 'uhaul*acyclical*motorcycle break down');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/23', '-61', 'uhaul*acyclical*motorcycle break down');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/24', '333', 'tithe');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/24', '-23', 'groceries*wegmans: chicken, tots, pizza');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/24', '-15', 'groceries*harris teeter');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/24', '-9', 'groceries*costco: cereal');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/24', '+55', 'uhaul*acyclical*motorcycle break down');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/25', '-45', 'electricity*regular bill');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/23', '-50', 'acyclical*homestead garden apartments application fee');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/26', '-34', 'groceries*harris teeter: juice, chicken');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/27', '-48', 'car safety inspection and emissions');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/28', '-15', 'gas');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/29', '-4', 'groceries*harris teeter');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/29', '-10', 'groceries*wegmans');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/30', '-16', 'gas');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/30', '-35', 'groceries*harris teeter');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/30', '-2', 'groceries*costco: bananas');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/30', '-8', 'cook out*eating out');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/31', '-210', 'citi*credit card');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('10/31', '-34', 'county personal property tax');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('11/1', '-13', 'groceries*wegmans: sports drink');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('11/1', '-27', 'groceries*harris teeter: tortillas, beef, eggs, jalapenos, spices');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('11/1', '-112', 'hoa');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('11/4', '+2368', 'paycheck');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('11/4', '-13', 'popeyes*eating out');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('11/3', '-6', 'chick fil a*eating out');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('11/3', '-20', 'apple*acyclical');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('11/5', '-19', 'gas');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('11/5', '-10', 'walmart: trash bags, candy');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('11/5', '-20', 'solo pizza*eating out');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('11/5', '-48', 'motorcycle thermostat');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('11/5', '-260', 'prius rear wheel bearings and hubs');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('11/5', '-119', 'internet');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('11/7', '-333', 'tithe');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('11/7', '-30', 'mobile');
INSERT INTO purchase_entity (pe_date, pe_dollars, pe_tag_string) VALUES ('11/9', '10', 'groceries*wegmans: gatorade powder');